name: Build Tools

on:
  push:
    branches:
      - oz/ci # TODO: change this

jobs:
  build-mac:
    runs-on: macos-latest
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install just ninja
      - name: Clone
        run: just clone
      - name: Prepare
        run: just prepare
      - name: Build rust, cargo and newlib
        run: just build-all
      - name: Package
        env:
          APPLE_CODESIGN_IDENTITY: ${{ secrets.APPLE_CODESIGN_IDENTITY }}
          APPLE_CRED: ${{ secrets.APPLE_CRED }}
          APPLE_P12_BASE64: ${{ secrets.APPLE_P12_BASE64 }}
          APPLE_P12_PASSWORD: ${{ secrets.APPLE_P12_PASSWORD }}
          APPLE_TEAMID: ${{ secrets.APPLE_TEAMID }}
          APPLE_TEMPKEYCHAIN_PASSWORD: ${{ secrets.APPLE_TEMPKEYCHAIN_PASSWORD }}
        run: just package
      - uses: actions/upload-artifact@v4
        with:
          name: platform-tools-osx-aarch64.tar.bz2
          path: out/platform-tools-osx-aarch64.tar.bz2

  build-linux:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install ninja
        run: sudo apt update; sudo apt install ninja-build
      - name: Clone
        run: just clone
      - name: Prepare
        run: just prepare
      - name: Build rust, cargo and newlib
        run: just build-all
      - name: Package
        run: just package
      - uses: actions/upload-artifact@v4
        with:
          name: platform-tools-linux-x86_64.tar.bz2
          path: out/platform-tools-linux-x86_64.tar.bz2
