name: Build Tools

on:
  push:
    branches:
      - oz/ci

jobs:
  build-mac:
    runs-on: macos-latest
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install just ninja
      - name: Prepare and build
        run: just all
